### ISSUE TITLE
登录功能实现

### ISSUE THREAD

**Issue by chshihang** [mengyunzhi/sign-in-through-code-scanning#102]

**Comment by teacherpan** [comment]
登录及验证实现思路:
1、在html文件中都是跳转到login控制器的login方法 ---- 控制器还是分开比较好，可以在控制器分别调用UserModel中的login(username, password, role)方法来完成登录。
2、通过html文件的hidden 输入传入equipment字段（）
浏览器在发起登录时，请求的header信息中会携带使用的浏览器的信息，通过该信息可以获取到是移动设备还是电脑。
![image](https://user-images.githubusercontent.com/12424383/160625121-837111b7-0e60-40e9-af06-aeccedc4f369.png)

3、调用user.php中的login方法(user中还有islogin和loginOut方法) -- 可以在login方法增加role参数
4、教师和admin通过number、password在user表匹配信息进行登录 ---- 学生也是如此

5、通过是否存在手机号判断学生是否注册，如果已注册就验证学生学号和密码  ---- 学生上来需要先注册，注册的时候输入手机号、学号、姓名和密码；注册后，就可以自主登录了。而是否已注册，可以用一个字段state状态来决定。该字段可以放到学生表或是user表中。

6、失败返回登录界面，成功跳转主页
7、分别在三个模块的index控制器中加登录验证

login方法具体内容：
1.在login的层的login方法中接收数据(username ; password, role)
2.调用user.php中的login
3.利用username在user表中查找对应用户(假设用户已存在)，然后进行密码校验。  
4.利用用户的role字段来校验角色是否与传入的role相同。相同，返回 true;不同返回false表示无权限

在根控制器中，获取用户访问的浏览器类型（移动或是电脑），如果用户使用的是手机，访问的却是电脑界面，则跳转至电脑界面。反之亦然。 如果我们只支持一种类型（比如只支持电脑端），则不对用户使用的浏览器类型加以判断。

在写功能时，可以先把逻辑的方法都写上，把返回值使用模拟值来代替，比如login(username, password, role) {return true}
后期在分工做比较。
