### ISSUE TITLE
教师端排课管理增加和修改

### ISSUE THREAD

**Issue by chshihang** [mengyunzhi/sign-in-through-code-scanning#121]

**Comment by chshihang** [comment]
![Uploading image.png…]()
实现当前页面的添加项目，添加上课时间，添加上课班级，以及编辑功能
添加项目:通过course_id 获取课程然后一对多添加项目
添加上课时间： 用添加课程中的 课程表 的代码
添加上课班级： 用添加课程中的 上课班级 的代码

**Comment by teacherpan** [comment]
上课时间相关的那个表再想想，主要是还是在老师发起签到、学生签到时，如何正确的获取到学生老师当前时间对应的 调度 信息。

**Comment by teacherpan** [comment]
当前我们的课程只考虑大节：

**Comment by teacherpan** [comment]
一天五大节，11小节。最后一大节是3小节（3个课时）。写死就行。

**Comment by teacherpan** [comment]
先把数据直接手动的维护到数据表中，然后查一下试试。

**Comment by teacherpan** [comment]
如果功能能实现，则说明数据表设计的正确，接下来再做数据添加。如果不正确，那就改数据表。这样可以减少无用功。

**Comment by chshihang** [comment]
是查添加课程的时候其他的数据表新增的数据是否正确吗

**Comment by chshihang** [comment]
11小节中 1-2，3-4,  5-6，7-8 ，9-11共五大节，根据选的小节判断是哪一大节，调度表开始时间和结束时间是当天 某一大节 所处的 秒数时间段

**Comment by chshihang** [comment]
删掉开始时间和结束时间字段，添加lesson字段记录第几大节，根据lesson确定上课时间和下课时间

**Comment by teacherpan** [comment]
> 是查添加课程的时候其他的数据表新增的数据是否正确吗

差不多是这意思，就是用核心功能检测其它的数据表我们设计的是否正确。不正确就先改表结构，成本低。
如果把新增都做出来了，做后核心功能的时候发现其它表错了，但其它表的新增啥的都有了，改起来成本就高了。
所以我们一般都会做核心的，那些还没想太清的功能。
至于一些简单的功能，只是时间问题。我们会放后面做。

**Comment by chshihang** [comment]
将dispatch的 字段改成 
id 
schedule_id 
week 
lesson 
create_time update_time

**Comment by chshihang** [comment]
修改添加课程的时候可以添加多个教室

**Comment by chshihang** [comment]
courseSort（排课管理主页面）自动优先选择课程的 思路：
1、在dispatch表添加  time  字段
2、当教师进入courseSort页面，找到dispatch表中每一个 schedule_id 对应的许多个课程的时间，通过每个时间求出和当前时间相差最小的时间，并把相差时间存入到 schedule表的 time的字段
3、从schedule表中查询数据（根据相差时间从小到大排序）

**Comment by teacherpan** [comment]
time字段代表什么呢？

**Comment by teacherpan** [comment]
开始上课的时间？
结束上课的时间？

**Comment by chshihang** [comment]
time字段代表 访问这个页面的时候的时间 和 最近的上课时间的相差时间
