### ISSUE TITLE
原型 管理端-》教师管理 -》index

### ISSUE THREAD

**Issue by zhangrui-18526443168** [mengyunzhi/sign-in-through-code-scanning#235]
![image](https://user-images.githubusercontent.com/86513476/169433986-5d7d0a26-d1b3-456a-ad3c-e79223e7414b.png)

**Comment by HHepan** [comment]
### 
<img width="947" alt="1654428931185_FDC4AEA3-7E9B-4e63-BB72-8BFFAF3E98E1" src="https://user-images.githubusercontent.com/100888986/172048564-624b6d77-fe26-422d-a33b-8c3f735f7bcd.png">
