### ISSUE TITLE
注销bug

### ISSUE THREAD

**Issue by zhangrui-18526443168** [mengyunzhi/sign-in-through-code-scanning#308]
点击注销后，url不改变。更换role登录，任然访问第一次登录role的页面
![1](https://user-images.githubusercontent.com/86513476/176639120-9189b2f6-2118-4418-a21a-7af2c0eebbee.png)
![2](https://user-images.githubusercontent.com/86513476/176639132-b21816f2-9449-4eb2-8055-a814e0e3fcc6.png)
![3](https://user-images.githubusercontent.com/86513476/176639137-68dce148-defc-460d-99a6-d1b1ae4cb034.png)

**Comment by teacherpan** [comment]
为登录界面单独定制一个路由，是解决此类问题比较有效的方法。
