### ISSUE TITLE
学习actions, workflows，尝试添加个后台机器人

### ISSUE THREAD

**Issue by teacherpan** [mengyunzhi/sign-in-through-code-scanning#452]
后台刚刚初始化，还有添加的机会，后面代码越来越多，一跑都是错，就不好添加了。

![image](https://user-images.githubusercontent.com/12424383/198858725-e7644bed-8ba4-460c-a34a-267b0265a003.png)

https://github.com/mengyunzhi/sign-in-through-code-scanning/actions

**Comment by chshihang** [comment]
收到
