### ISSUE TITLE
我将要做什么。

### ISSUE THREAD

**Issue by teacherpan** [mengyunzhi/sign-in-through-code-scanning#95]

**Comment by teacherpan** [comment]
思路：
1. 第一步：xxx
2. 第二步：xxx

**Comment by chshihang** [comment]
目前思路:
1、设计er图
2、管理员模块和教师模块的各项增删改查
3、提管理员和教师模块的各项issue
4、issue实现和学生的扫码签到

**Comment by teacherpan** [comment]
优先设计 ER 图。ER 图不对的话，说明对整个系统的了解还不到位。
