### ISSUE TITLE
设计 ER 图。

### ISSUE THREAD

**Issue by teacherpan** [mengyunzhi/sign-in-through-code-scanning#97]

**Comment by HHepan** [comment]
<img width="233" alt="1648553992492_0C6220AC-0A43-43e5-9E46-F623C89EDDDC" src="https://user-images.githubusercontent.com/100888986/160603446-33704e5b-6411-4c79-9682-c99adf35e682.png">

**Comment by HHepan** [comment]
<img width="351" alt="1648902522928_447550E4-C653-43c5-BBA9-EF5107D77666" src="https://user-images.githubusercontent.com/100888986/161383452-ec970c3b-0188-4252-8d79-61593b8e7397.png">
班级和课程改为多对多

**Comment by teacherpan** [comment]
大体上没有问题。

**Comment by teacherpan** [comment]
修正几点：
1. 课程和 ROOM 没有关系。
2. 少一个最重要排课（也就是课程表）
3. 课程与班级多对多的时候，和学生也是多对多的关系。

哪不理解或有异义的话直接评论。

**Comment by HHepan** [comment]
课程里不是有一个信息是教室吗？

**Comment by chshihang** [comment]
![c6bb153a606c3da0033d27b3ae2d8bc7ae9057965f48bc6a963767659bd58419QzpcVXNlcnNcREVMTFxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcOTUyMzEzOTM3X3YyXEltYWdlRmlsZXNcMTY0OTA1NTM5MzgxOF9FOTkzNjVCNS01OEY3LTRkMzctODRDNi1EM0ZCQkVGN0Y3MzcucG5n](https://user-images.githubusercontent.com/96906188/161490037-8109b241-7782-4d8f-8988-a621168d7ca7.png)

**Comment by chshihang** [comment]
![c6aaa834358b4c42a011c428132fd8306bbd2c0035e876b03d71a74a49d28b4cQzpcVXNlcnNcREVMTFxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcOTUyMzEzOTM3X3YyXEltYWdlRmlsZXNcMTY0OTA2NTAxMjU0OF82QjJDNDA0Ri0zMjQ4LTRhYmYtOEMxNy1DMkJGMUY2NDI4NTUucG5n](https://user-images.githubusercontent.com/96906188/161535989-de6a60bb-eca3-431b-809d-db87f948285a.png)

**Comment by chshihang** [comment]
![1649072985425_B8279AAC-07BC-46f7-AC27-6A4EC09340C2](https://user-images.githubusercontent.com/96906188/161537829-b6e636be-3fb6-4a96-a070-aab24b8d2c5d.png)

**Comment by chshihang** [comment]
![image](https://user-images.githubusercontent.com/96906188/161654031-9f09483f-c8c1-437e-bf99-6c95b77d50eb.png)

**Comment by teacherpan** [comment]
大体上没问题。字段待开发过程中再补充。

**Comment by teacherpan** [comment]
在开发过程中，发现问题了我们继续再此讨论。

**Comment by teacherpan** [comment]
在项目根目录下，创建一个document文件夹，然后把这个图上的源文件放里面并提交上来。
